on:
  workflow_dispatch:
  push:

name: Build and push
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix_data: ${{ steps.list.outputs.matrix_data }}
    container:
      image: python:latest
    steps:
      - uses: actions/checkout@v3
      - uses: jitterbit/get-changed-files@v1
        id: files_changed

      - name: Get matrix data
        id: list
        run: python3 .github/workflows/scripts/get_matrix_data.py
        env:
          CHANGED: "${{ steps.files_changed.outputs.added_modified }}"
          EVENT_NAME: "${{ github.event_name }}"

  validate:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        context: ${{ fromJSON(needs.prepare.outputs.matrix_data) }}

    name: Validate data for actions-images:${{ matrix.context.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Check tag
        run: |
          [ -n "${{ matrix.context.tag }}" ]
      - name: Check file
        run: |
          [ -f "${{ matrix.context.file }}" ]

  build:
    runs-on: ubuntu-latest
    needs: [prepare, validate]
    strategy:
      matrix:
        context: ${{ fromJSON(needs.prepare.outputs.matrix_data) }}

    name: Build actions-images:${{ matrix.context.tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.hub.docker.com/joscherrer/actions-images
          tags: type=raw,value=${{ matrix.context.tag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "${{ matrix.context.file }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
